Initial implementation
thoth-station/revsolver pull request #1
Opened 2020-04-21 22:12 UTC by fridex

2020-04-21 22:12 UTC, sesheta commented
Thanks for Opening the Pull Request

2020-04-21 22:14 UTC, goern requested changes

2020-04-21 22:14 UTC, goern commented on CHANGELOG.md
>  # Changelog for Thoth's Template GitHub Project
this is not template

2020-04-21 22:18 UTC, fridex commented on CHANGELOG.md
>  # Changelog for Thoth's Template GitHub Project
Fixed in 28daae4

2020-04-27 08:40 UTC, pacospace approved these changes
Amazing! Thanks!! :coffee:

2020-04-27 08:41 UTC, fridex commented
Merging manually until zuul will be configured.

2020-04-27 08:41 UTC, merged

2020-04-27 08:42 UTC, sesheta commented
Successfully Merged.
  Thanks for the contribution.